### ISSUE TITLE
USB: usb_device_handle_win.cc

### ISSUE THREAD

**Issue by zeus1921** [stavros-melidoniotis/ig-tagger#3]
```

C:\Users\Admin\Desktop\ig-tagger-master\ig_tagger.py:54: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  chrome = webdriver.Chrome(ChromeDriverManager().install())

DevTools listening on ws://127.0.0.1:51848/devtools/browser/828d8fc0-3997-46b6-b841-160fd7b578db
[10868:2148:1116/214808.426:ERROR:device_event_log_impl.cc(215)] [21:48:08.426] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Um dispositivo ligado ao sistema nÒo estß a funcionar. (0x1F)
[10868:2148:1116/214808.438:ERROR:device_event_log_impl.cc(215)] [21:48:08.437] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Um dispositivo ligado ao sistema nÒo estß a funcionar. (0x1F)
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\ig-tagger-master\ig_tagger.py", line 72, in <module>
    WebDriverWait(chrome, 15).until(EC.presence_of_element_located((By.XPATH, LOGGED_XPATH)))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00F4ACD3+2075859]
        Ordinal0 [0x00EDEE61+1633889]
        Ordinal0 [0x00DDB7BD+571325]
        Ordinal0 [0x00E0AC2F+764975]
        Ordinal0 [0x00E0AE1B+765467]
        Ordinal0 [0x00E3D0F2+970994]
        Ordinal0 [0x00E27364+881508]
        Ordinal0 [0x00E3B56A+963946]
        Ordinal0 [0x00E27136+880950]
        Ordinal0 [0x00DFFEFD+720637]
        Ordinal0 [0x00E00F3F+724799]
        GetHandleVerifier [0x011FEED2+2769538]
        GetHandleVerifier [0x011F0D95+2711877]
        GetHandleVerifier [0x00FDA03A+521194]
        GetHandleVerifier [0x00FD8DA0+516432]
        Ordinal0 [0x00EE682C+1665068]
        Ordinal0 [0x00EEB128+1683752]
        Ordinal0 [0x00EEB215+1683989]
        Ordinal0 [0x00EF6484+1729668]
        BaseThreadInitThunk [0x75867BA9+25]
        RtlInitializeExceptionChain [0x7734BB3B+107]
        RtlClearBits [0x7734BABF+191]
```

**Comment by zeus1921** [comment]
it's working, i don't know what i'v done lol.
